### ISSUE TITLE
Selected/Deselecting a Node in Python does not update selected_nodes in Tree

### ISSUE THREAD

**Issue by sanbales** [QuantStack/ipytree#10]
When changing a node's `selected` property in Python, it does not seem to trigger the update in the tree's `selected_nodes`.  At least most of the times.  Sometimes it does, but (at least in my cases) it is seldom the case.

Open to suggestions/comments/ideas.

```
Python: 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
IPyWidgets: 7.5.0
JupyterLab: 1.0.2
Traitlets: 4.3.2
```

Added a sleep to see if it is a race condition, but it did not resolve the issue...

```
import time
from ipytree import Node, Tree

tree = Tree(nodes=[Node("root", nodes=[Node("Leaf 1"), Node("Leaf 2")])])

leaf_1 = tree.nodes[0].nodes[0]
leaf_1.selected = True

display(tree)
# time.sleep(0.5)

assert leaf_1.selected, "leaf_1 is not selected"
assert leaf_1 in tree.selected_nodes, "leaf_1 is not in selected nodes!"
```
![image](https://user-images.githubusercontent.com/1438114/62101717-5ee43a80-b264-11e9-955d-92fc63d639df.png)

**Comment by martinRenou** [comment]
Thanks a lot for the report

**Comment by sanbales** [comment]
I'd like to thank the ipytree team for all their improvements in the latest version.  It's been working great!

Was wondering if there had been ideas on how to address this issue, or maybe there is a workaround that could be done to send the selection to the front-end, or it is an underlying issue with `jsTree`?

**Comment by martinRenou** [comment]
I am tempted to say that `selected_nodes` does not contain `leaf_1` in your example because it hasn't done the Python<->JavaScript roundtrip yet. `selected_nodes` being updated by jstree for now, you need to wait for the tree to be displayed on the page before you can access this property.

Now we might want to update this property Python side.

**Comment by sanbales** [comment]
Thank you, Martin.  You were correct.
