### ISSUE TITLE
recursively create node similar to file explorer

### ISSUE THREAD

**Issue by shek2994** [QuantStack/ipytree#12]
Hi @martinRenou , 

How do I recursively create node based on json content. For ex: if my json has key:val pair based on my directory structure, How do i use Tree() and Node() to recursively create widgets.

my json is : 
`res={'home': {'james': {'Downloads': {'data': {'data19': {'20190207': {'adc1': '5' }}}}}}}`

I tried using recursively as in this [link](https://stackoverflow.com/a/54000999/12398200), but not much success

**Comment by martinRenou** [comment]
Hello,

Could you please provide the code you tried to execute?

**Comment by shek2994** [comment]
Here is pseudo code. I want to have a similar logic and with Node() method called recursively when dict() reaches end point. 

`res={'home': {'james': {'Downloads': {'data': {'data19': {'20190207': {'ADC': '5' }}}}}}}

import json
from ipytree import Tree, Node 

def walk(d):
   global path
   for k,v in d.items():
      if isinstance(v, str) or isinstance(v, int) or isinstance(v, float):
         path.append(k)
         print("{}={}".format(".".join(path), v)) 
         path.pop()
      elif v is None:         
         path.append(k)
         # do something special
         path.pop()
      elif isinstance(v, list):         
         path.append(k)
         if len(v) == 1 :
             path.pop()
         else:
             for v_int in v:                
                walk(v_int)
             path.pop()
      elif isinstance(v, dict):         
         path.append(k)
         walk(v)         
         path.pop()
      else:
         print("###Type {} not recognized: {}.{}={}".format(type(v), ".".join(path),k, v))


path = []
walk(res)`

output should be:
![image](https://user-images.githubusercontent.com/35740092/70111314-d2b1ac00-1677-11ea-8468-5d178ce0dfc7.png)

**Comment by shek2994** [comment]
@martinRenou 
Below code uses fixed set of nodes. I want to make it recursive and use node name from json.

```
from ipytree import Tree, Node

tr=Tree()

a=Node('a')
b=Node('b')
c=Node('c')
d=Node('d')

c.add_node(d)
b.add_node(c)
a.add_node(b)

tr.add_node(a)
```
```
tr
```
output:
![image](https://user-images.githubusercontent.com/35740092/70112915-1ce95c00-167d-11ea-9aee-bffb62e5234f.png)

**Comment by martinRenou** [comment]
I wouldn't go through this `path2` variable in order to create the tree, also it's a global variable and global variables are evil. Well, everything is global in Jupyter but that's a special context.

Simply define a `populate` function like the following (I did not test that code, so you might need to change one or two things to make it work):

```python
json = {'home': {'james': {'Downloads': {'data': {'data19': {'20190207': {'adc': '5' }}}}}}}

def populate(node, json):
    for key, value in json.items():
        leaf = Node(key)
        
        if isinstance(value, dict):
            populate(leaf, value)
        
        node.add_node(leaf)

tree = Tree()
populate(tree, json)
tree
```
