### ISSUE TITLE
Error displaying widget in "ipytree: Tree widget" example

### ISSUE THREAD

**Issue by candronikos** [QuantStack/ipytree#2]
Testing in jupyter lab following the install instructions provided.

Getting the error "Error displaying widget" when trying to display the widget.

**Comment by jakirkham** [comment]
Also was not able to get this to work in JupyterLab. Was able to get it to work in the regular Jupyter Notebook. Are there other install steps that we need to do?

**Comment by martinRenou** [comment]
Sorry for the late reply, I was not watching the repo. Yes you need to run:
```
jupyter labextension install ipytree
```
after the installation

You might also need to run
```
jupyter labextension install @jupyter-widgets/jupyterlab-manager
```
If it still doesn't work

**Comment by martinRenou** [comment]
I'll add it to the README asap

**Comment by NumesSanguis** [comment]
I'm also getting this same error with JupyterLab, so I tried your recommendation (I already have jupyterlab-manager and ipytree as JupyterLab  add-on):

```
git clone https://github.com/QuantStack/ipytree.git
cd ipytree/
jupyter labextension install js
```
and now it works.
I guess it slipped your mind to add these instructions to the README @martinRenou ?
Just a tip, don't close any issue until the change has hit master.

Would it be possible to add this functionality to `ipytree lab extension`, so people don't have to git clone this repo?

Thanks for the great work of this Extension!

**Comment by martinRenou** [comment]
> I guess it slipped your mind to add these instructions to the README @martinRenou ? Just a tip, don't close any issue until the change has hit master.

Maybe I misunderstand what you think is missing, but I can see the correct instructions in the README.

> Would it be possible to add this functionality to ipytree lab extension, so people don't have to git clone this repo?

What do you mean? It is not mandatory to git clone the repo, only for development installation you need to do it.
```
conda install -c conda-forge ipytree
jupyter labextension install @jupyter-widgets/jupyterlab-manager ipytree
```
works just fine.

**Comment by NumesSanguis** [comment]
I was referring to these instructions:

> Sorry for the late reply, I was not watching the repo. Yes you need to run from the ipytree repo root dir:
> 
> ```
> jupyter labextension install js
> ```

I ran the following code (a few weeks ago, so not entirely sure what I did):

```
conda install -c conda-forge ipytree
jupyter labextension install @jupyter-widgets/jupyterlab-manager ipytree
```

However, I still got the OPs issue of: "Error displaying widget" when trying to display the widget.

Only after running `jupyter labextension install js` did the widget display in JupyterLab. Even though the README suggests that this only necessary if you're doing any development, not a normal install. Or did I understand it wrongly?

**Comment by martinRenou** [comment]
Can you tell me which ipympl and JupyterLab version you have? I would suggest using latest

**Comment by ltalignani** [comment]
Testing in Jupyter Notebook 6.3.0
I used 

 `from ipytree import Tree, Node`

for my callset. When I try to see the tree 
 
`callset.tree(expand=True)`

Notebook return just these 

`Tree(nodes=(Node(disabled=True, name='/', nodes=(Node(disabled=True, name='2L', nodes=(Node(disabled=True, nam…`

but I can't see the tree. I also checked the README.md, installed js and jsTree, but still not working.
