### ISSUE TITLE
High severity vulnerability in jstree@3.3.5 dependency; consider specifying dependency as range

### ISSUE THREAD

**Issue by telamonian** [QuantStack/ipytree#21]
Currently I'm unable to use ipytree due to a [high severity vulnerability](https://snyk.io/vuln/SNYK-JS-JSTREE-72490) in one of the dependencies, jstree@3.3.5:

> Affected versions of this package are vulnerable to Arbitrary Code Injection. due to using the eval() function in an insecure manner.

Could you please update your dependency to the latest jstree (3.3.9) and then do a new release of ipytree?

Also, could you please consider specifying the jstree dependency as a range (`^3.3.9`) instead of a pin (`3.3.9`) to a particular patch version? `~3.3.9`, for example, may be helpful for mitigating any future security risks, since security updates are typically patch releases.

**Comment by martinRenou** [comment]
Would you mind opening a PR? I'd be happy to merge it and do a release quickly after that

**Comment by martinRenou** [comment]
`0.1.6` is released with your fix, thanks! It is available on PyPi (through `pip install`) but not on `conda` yet

**Comment by telamonian** [comment]
Thanks Martin! I've already pulled the new version into my deployment
