### ISSUE TITLE
Is there anyway to port this into colab?

### ISSUE THREAD

**Issue by Kreijstal** [QuantStack/ipytree#32]
I'd like this to work with [colab](https://colab.research.google.com/github/QuantStack/ipytree/blob/master/examples/ipytree.ipynb), is this in general really hard to achieve? 

I've done some research and google colab does support ipywidgets 7.5.0, as you can see on this example [colab](https://colab.research.google.com/github/jupyter-widgets/ipywidgets/blob/7.x/docs/source/examples/Variable%20Inspector.ipynb) the problem with ipytree is that the trees appear blank as if there is no html to be shown, does anyone know why is this? Internally it seems to be working fine.

I'd fix it myself but I wouldn't know how to start debugging this problem.
![image](https://user-images.githubusercontent.com/2415206/85200148-368a8200-b2f5-11ea-977c-e26d180f1190.png)
As you can see trees appear blank

![image](https://user-images.githubusercontent.com/2415206/85200160-4ace7f00-b2f5-11ea-8710-29ec4ff9098d.png)
representation of the tree seems to work fine, but dom_classes is empty, should it be empty?

**Comment by martinRenou** [comment]
Google colab does not support custom interactive widgets libraries, this is something that should be fixed in colab, we cannot do anything about it in ipytree unfortunately. You can follow the status of this here: https://github.com/googlecolab/colabtools/issues/60

**Comment by tylere** [comment]
Fyi, I filed a specific Colab issue for ipytree support: googlecolab/colabtools#2522

**Comment by blois** [comment]
`ipytree==0.2.0` appears to work in Colab when custom widgets are enabled (see example in https://github.com/googlecolab/colabtools/issues/2522). 

With `ipytree==0.2.1` it's failing to find /dist/index.js. This is included in the published files to npm for `0.2.0` but not `0.2.1`. 

I believe this was a result of https://github.com/QuantStack/ipytree/commit/81e125e61c259aed3a09d396f83fd0d1cee833cf#diff-e51a40ac250c9696142466f114f754161e7e5102c0cdb5354548b757deb272f6?
