### ISSUE TITLE
Listen for the "expand node" event to load child nodes on demand

### ISSUE THREAD

**Issue by sliedtkegranta** [QuantStack/ipytree#33]
Many thanks for creating this great widget!

I am wondering, is there is a way to listen for the "expand node" event to fetch and add child nodes on demand?

**Comment by martinRenou** [comment]
That is a great idea, and yes I think you can do it.

This should work
```python
def add_children(event):
    is_open = event['new']

    if is_open:
        node.add_node(Node("test!"))

node.observe(add_children, "opened")
```

Although be sure to have at least one child node already, otherwise you won't have the "expand" button displayed.

**Comment by martinRenou** [comment]
Or you could do the same by listening to the "selected" state change, so that you would add child nodes when clicking on the node instead of the "expand" button.

```python
node.observe(add_children, "selected")
```

**Comment by sliedtkegranta** [comment]
Great, that works perfectly. Many thanks!

**Comment by martinRenou** [comment]
Sure! Happy to help
