### ISSUE TITLE
ipytree.ipynb example code does not work with windows OS

### ISSUE THREAD

**Issue by shek2994** [QuantStack/ipytree#37]
```
from ipytree import Tree, Node
tree = Tree(stripes=True)
tree
```
Error message : Error displaying widget: model not found

Then I ran this cmd :
`jupyter nbextension enable --py --sys-prefix ipytree`

Now it is struck at `Loading widget...`

Appreciate your help to resolve this issue

Here are package and version details:
!jupyter --version
jupyter core     : 4.6.3
jupyter-notebook : 6.0.3
qtconsole        : 4.7.5
ipython          : 7.16.1
ipykernel        : 5.3.2
jupyter client   : 6.1.6
jupyter lab      : 1.2.18
nbconvert        : 6.0.4
ipywidgets       : 7.5.1
nbformat         : 5.0.7
traitlets        : 4.3.3

# Name                    Version                   Build  Channel
ipython                   7.16.1           py38h5ca1d4c_0  
ipython_genutils          0.2.0                    py38_0  
kafka-python              1.4.7                    pypi_0    pypi
msgpack-python            1.0.0            py38h74a9793_1  
python                    3.8.3                he1778fa_2  
python-dateutil           2.8.1                      py_0  
python-editor             1.0.4                      py_0  
python-engineio           3.13.2                   pypi_0    pypi
python-json-logger        0.1.11                     py_0  
python-jsonrpc-server     0.3.4                      py_1  
python-language-server    0.34.1                   py38_0  
python-libarchive-c       2.9                        py_0  
python-socketio           4.6.0                    pypi_0    pypi
python_abi                3.8                      1_cp38    conda-forge

**Comment by martinRenou** [comment]
Are you using JupyterLab or Jupyter Notebook?

**Comment by shek2994** [comment]
I am using jupyter notebook

**Comment by martinRenou** [comment]
Can you show the output of the following commands?

`jupyter nbextension list`

`which pip`
`which python`
`python -c "import ipytree; print(ipytree._version.version_info)"`

**Comment by shek2994** [comment]
```
 notebook section
      ipytree/extension enabled
      - Validating: ok
      jupyter-webrtc/extension enabled
      - Validating: ok
      jupyter-datawidgets/extension enabled
      - Validating: ok
      jupyter-threejs/extension enabled
      - Validating: ok
      plotlywidget/extension enabled
      - Validating: ok
      voila/extension enabled
      - Validating: ok
      jupyter-js-widgets/extension enabled
      - Validating: ok
```

```
pip 20.2.3
Python 3.8.3
python -c "import ipytree; print(ipytree._version.version_info)"
(0, 1, 8)
```

**Comment by martinRenou** [comment]
Did you actually run `which pip` and `which python` those should show the location of the binaries, not the version.
It might be interesting to know `which jupyter` as well

The nbextension seems correctly installed, but I suspect your installation is broken, maybe because jupyter and ipytree don't leave in the same virtual env/conda env.

Do you use conda?

**Comment by shek2994** [comment]
Sorry/apology, I did a fresh installation with new conda env and it did work. Sorry for that.
fyi, these are the details:

```
  config dir: c:\users\som\anaconda3\envs\py37\etc\jupyter\nbconfig
    notebook section
      ipytree/extension enabled
      ipyvolume/extension enabled
      jupyter-webrtc/extension enabled
      jupyter-datawidgets/extension enabled
      jupyter-matplotlib/extension enabled
      jupyter-threejs/extension enabled
      plotlywidget/extension enabled
      voila/extension enabled
      jupyter-js-widgets/extension enabled

(py37) C:\Users\som>which pip
which pip
/c/Users/som/anaconda3/envs/py37/Scripts/pip

(py37) C:\Users\som>which python
which python
/c/Users/som/anaconda3/envs/py37/python

(py37) C:\Users\som>python -c "import ipytree; print(ipytree._version.version_info)"
python -c "import ipytree; print(ipytree._version.version_info)"
(0, 1, 5)

```
(py37) C:\Users\som>

**Comment by martinRenou** [comment]
No worries :) It's always good to start with a fresh environment. 

Note that running `jupyter nbextension enable --py --sys-prefix ipytree` manually should **not** be needed when not doing a dev installation.
