### ISSUE TITLE
Attributes?

### ISSUE THREAD

**Issue by paris0120** [QuantStack/ipytree#42]
I went briefly through the example but didn't find how to add attributes to a node which can be used as arguments with events. Did I miss something?

**Comment by martinRenou** [comment]
I am sorry, I don't really understand your request.

What kind of use-case do you have in mind? Could you provide some code that would express the kind of API you are lacking?

**Comment by paris0120** [comment]
Sorry, my bad. I saw how it works with hierarchy.
