### ISSUE TITLE
ipytree CDN is missing /dist in @0.2.1

### ISSUE THREAD

**Issue by tylere** [QuantStack/ipytree#57]
The /dist directory is present @0.2.0
https://www.jsdelivr.com/package/npm/ipytree?version=0.2.0

but it is missing @0.2.1
https://www.jsdelivr.com/package/npm/ipytree

This is preventing ipytree from working in Colab (at least without pinning the version):
https://github.com/googlecolab/colabtools/issues/2522#issuecomment-998288289

**Comment by tylere** [comment]
The /dist directory only seems to be missing from @0.2.1. The previous versions all have the /dist directory:

- https://www.jsdelivr.com/package/npm/ipytree?version=0.2.0&path=dist
- https://www.jsdelivr.com/package/npm/ipytree?version=0.1.8&path=dist
- https://www.jsdelivr.com/package/npm/ipytree?version=0.1.7&path=dist
- https://www.jsdelivr.com/package/npm/ipytree?version=0.1.6&path=dist
- https://www.jsdelivr.com/package/npm/ipytree?version=0.1.5&path=dist
- etc...

**Comment by martinRenou** [comment]
This should be fixed with 0.2.2 https://www.jsdelivr.com/package/npm/ipytree?version=0.2.2&path=dist

Sorry for the inconvenience.
