### ISSUE TITLE
Alternative representations

### ISSUE THREAD

**Issue by jakirkham** [QuantStack/ipytree#8]
It might be nice to have alternative representations (like HTML) so that trees will render with nbviewer. For example [this tree]( https://nbviewer.jupyter.org/gist/jakirkham/aa9ffd9bf8cdca48db2c26334f5bfe74#Display-tree ) doesn't render in nbviewer. Though it appears to lack the state to do so.

**Comment by martinRenou** [comment]
I never do this, but did you check: https://ipywidgets.readthedocs.io/en/stable/embedding.html#rendering-interactive-widgets-on-nbviewer ?

**Comment by jakirkham** [comment]
Interesting. Thanks for the pointer. Was not aware of that.

Managed to get it to work with the Jupyter Notebook and have updated the Gist accordingly. Seems to work with nbviewer.

However was not able to figure out how to get this to work with JupyterLab. Though I may be doing something wrong here. Pointers welcome.

**Comment by martinRenou** [comment]
> However was not able to figure out how to get this to work with JupyterLab.

I am not sure I follow you. What does not work in JupyterLab? ipytree?

**Comment by jakirkham** [comment]
[This option]( https://ipywidgets.readthedocs.io/en/stable/embedding.html#rendering-interactive-widgets-on-nbviewer ) does not appear to exist with JupyterLab. The only similar thing I can find is
`File -> Save Notebook with View State`, but that doesn't appear to do the right thing. Again I'm probably do something wrong here.

**Comment by jakirkham** [comment]
After a little sleuthing, it appears this doesn't exist for JupyterLab, but will very soon.

xref: https://github.com/jupyter-widgets/ipywidgets/issues/2465
xref: https://github.com/jupyter-widgets/ipywidgets/issues/2063

**Comment by jakirkham** [comment]
Closing as resolved. Thanks for your help @martinRenou! 😄

Will follow the upstream issues for updates on JupyterLab support.

**Comment by martinRenou** [comment]
Sure :) Thanks for using ipytree!

**Comment by jakirkham** [comment]
Unrelated, but maybe of interest. Have started exploring using this in Zarr to represent hierarchy. ( https://github.com/zarr-developers/zarr-python/pull/450 ) It works really nicely! Thanks for all of the effort here. 🙂

**Comment by martinRenou** [comment]
That is super nice!!
