### ISSUE TITLE
ValueError: "ipytree" is not a valid npm package

### ISSUE THREAD

**Issue by junlei007** [QuantStack/ipytree#9]
~$ jupyter labextension install ipytree
An error occured.
ValueError: "ipytree" is not a valid npm package
See the log file for details:  /tmp/jupyterlab-debug-e_2mxgkn.log

**Comment by martinRenou** [comment]
Do you mind trying it again from an other directory? If you have an `ipytree` directory in the current location JupyterLab is a bit lost
